### ISSUE TITLE
The second test fails during TestSentimentClassifier in the SVM chapter

### ISSUE THREAD

**Issue by headwinds** [thoughtfulml/examples-in-python#21]
@hexgnu I'm really enjoying your book and I'm fairly new to data science so this could very well be my confusion but I think the second test may be failing due to an assertion error where it's expecting 0 but receives a fraction instead similar to the first test. 

From within the support_vector_machines  folder, I ran the test like so:
```
python -m unittest -v tests.test_sentiment_classifier.TestSentimentClassifier
```

The first test was OK but the second results in:

```
======================================================================
FAIL: test_validate_itself (tests.test_sentiment_classifier.TestSentimentClassifier)
yields a zero error when it uses itself
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brandonflowers/examples-in-python/support_vector_machines/tests/test_sentiment_classifier.py", line 54, in test_validate_itself
    self.assertEqual(total, 0)
AssertionError: Fraction(1, 5332) != 0

----------------------------------------------------------------------
```

**Comment by hexgnu** [comment]
Hey Brandon I'll work on this tomorrow morning and see what's happening :) thanks for submitting a ticket!

**Comment by hexgnu** [comment]
Hey Brandon, I just pushed a fix to this https://github.com/thoughtfulml/examples-in-python/commit/b4d744ad93b7976a6c4ca0db1054b3e045f74872 which should fix the problem.

Basically here's the issue: sometimes fractions which are close to 0 don't end up being zero :smile:
